using JuMP
import Ipopt

include("data.jl")

model = Model(Ipopt.Optimizer)

# Decision variables


@variable( # active power generated by generator i for all generators
    model,
    0 <= power_generated[i in generator_index] <= generator_capacities[i]
    #,start = generator_capacities[i]/2
)

@variable( # reactive power absorbed or generated by generator i
    model,
    -0.03 * generator_capacities[i] <= reactive_power[i in generator_index] <= 0.03 * generator_capacities[i]
    #,start = 0.0
)

@variable( # voltage amplitudes for each node
    model,
    0.98 <= voltage_amplitude[k in node_index] <= 1.02
    #,start = 1.0
)

@variable( # voltage phase angles for each node
    model,
    -pi <= voltage_angle[k in node_index] <= pi
    #,start = pi/2
)

# Helper functions


# active power flow from node k to l
p_kl(k, l) = (voltage_amplitude[k]^2) * G[k, l] - voltage_amplitude[k] * voltage_amplitude[l] * G[k, l] * cos(voltage_angle[k] - voltage_angle[l]) - voltage_amplitude[k] * voltage_amplitude[l] * B[k, l] * sin(voltage_angle[k] - voltage_angle[l])

# reactive power flow from node k to l
q_kl(k, l) = -(voltage_amplitude[k]^2) * B[k, l] + voltage_amplitude[k] * voltage_amplitude[l] * B[k, l] * cos(voltage_angle[k] - voltage_angle[l]) - voltage_amplitude[k] * voltage_amplitude[l] * G[k, l] * sin(voltage_angle[k] - voltage_angle[l])


# Constraints


@constraint( # active power balance for every node
    model,
    active_balance[k in node_index],
    sum(power_generated[i] for i in generator_index if generator_nodes[i] == k; init=0.0) - node_demands[k]
        ==
        sum(p_kl(k, l) for l in node_index)
)

@constraint( # reactive power balance for every node
    model,
    reactive_balance[k in node_index],
    sum(reactive_power[i] for i in generator_index if generator_nodes[i] == k; init=0.0)
        ==
        sum(q_kl(k, l) for l in node_index)
)


# Objective function


@objective(
    model,
    Min,
    sum(generator_costs[i] * power_generated[i] for i in generator_index)
)

optimize!(model)